### PR TITLE
Add gfm - for fetching origin master and merge 

### PR DESCRIPTION
**Pull request by WarFox**
gfm = git fetch origin master --prune; git merge FETCH_HEAD

Fetch origin master and merge with current branch

Simple PR

### CODE REVIEW

**Comment by jhillyerd** [comment]
Can you also add it to the readme? Thx

**Comment by WarFox** [comment]
I've updated readme, thanks @jhillyerd

**Comment by jhillyerd** [comment]
Have you tested this?  Looking at the abbr definition, I don't think it will work due to the `;`

```
> abbr -a 2test echo one; echo two
two
> abbr | grep 2test
abbr -a -U -- 2test 'echo one'
```

**Comment by WarFox** [comment]
You are right 👍 

I missed the surrounding double quotes earlier

**Comment by jhillyerd** [comment]
Thanks!

**Pull request merged**
