### PR TITLE
Add git push options

### PR DESCRIPTION
**Pull request by ilabacheuski**
Add comands: 
git push --no-verify
git push --no-verify --force-with-lease

### CODE REVIEW

**Comment by jhillyerd** [comment]
Thanks!  These look good, can you add them to the README.md also?

**Comment by ilabacheuski** [comment]
Sorry @jhillyerd I forgot about this PR. I will update today!

**Comment by ilabacheuski** [comment]
Done

**Comment by ilabacheuski** [comment]
@jhillyerd Are u there?

**Comment by jhillyerd** [comment]
Fell asleep at the wheel, thanks. :)

**Pull request merged**
