### PR TITLE
Add alias for rebasing against latest origin/main

### PR DESCRIPTION
**Pull request by UnsolvedCypher**
Add an alias for fetching the latest default branch and rebasing against it.

### CODE REVIEW

**Comment by jhillyerd** [comment]
These look similar to [ggu](https://github.com/jhillyerd/plugin-git/blob/3c01d375f784f3255b138575cbc290155ea39dd0/functions/ggu.fish) -- wonder if it would make sense to add a bit more functionality to it instead?

**Comment by jhillyerd** [comment]
oh wait, I see, yours are for main/master and ggu is for current branch.

**Comment by UnsolvedCypher** [comment]
Yes, if you think this would be better as something like `ggum` I'm happy to do that

**Comment by jhillyerd** [comment]
Looking at the current set, it seems that all the gg_ commands are focused on origin+current branch, so your current naming makes more sense to me.  I took a look at the oh my zsh project but didn't see anything similar to base ours on.

**Comment by jhillyerd** [comment]
Thanks!

**Pull request merged**
