### PR TITLE
Add commands

### PR DESCRIPTION
**Pull request by MartinDelille**
```
gsu: git submodule update
gban: git branch -a -v --no-merged 
```

### CODE REVIEW

**Comment by MartinDelille** [comment]
@jhillyerd any feedback on these new commands?

**Comment by jhillyerd** [comment]
Away from computer for a couple weeks

**Comment by jhillyerd** [comment]
Can you add gban and gsu to the README as well? Thanks.

**Comment by MartinDelille** [comment]
Oups sorry! I just update my PR.

**Comment by jhillyerd** [comment]
Thanks!

**Pull request merged**
