### PR TITLE
A better git log

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
With colors, date and author name

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
in fact i'll put all my modifs in my fork because i want to change several abbrs

**Comment by jhillyerd** [comment]
Thanks for these PRs, will try and review some of them this weekend

**Comment by jhillyerd** [comment]
Looks good, please add to README

**Comment by BarbzYHOOL** [comment]
Done.

For more of my changes, check my fork if curious, but I removed the readme list cause it's useless.

**Pull request merged**
